---
output:
  md_document:
    variant: markdown_github
---

```{r}
#rm(list = ls())
attach(InsectSprays)
#detach(InsectSprays)
data(InsectSprays)
str(InsectSprays)
InsectSprays

mean(count[spray=="A"])
tapply(count, spray, mean)
tapply(count, spray, var)
tapply(count, spray, length)

boxplot(count ~ spray)

Photoperiod <- ordered(spray, levels = c("F", "B", "C", "D", "E", "A"))
tapply(count, Photoperiod, mean)

```
```{r}
oneway.test(count ~ spray)
```

```{r}
aov.out = aov(count ~ spray, data = InsectSprays)
summary(aov.out)
```

```{r}
# 사후 검정
TukeyHSD(aov.out)
# 귀무가설: 두 스프레이 성능에 차이가 없다
# 대립가설: 두 스프레이 성능에 차이가 있다.
```
```{r}
summary.lm(aov.out)
```

```{r}
plot(aov.out)
```
```{r}
bartlett.test(count ~ spray, data = InsectSprays)
# 등분산성 검정의 하나
# 귀무가설: 종속변수의 분산은 모든 집단에서 서로 같다
# 대립가설: 종속변수의 분산은 모든 집단에서 서로 같지 않다.
# 
```

```{r}
# 비모수적 방법(anova test와 반대)
kruskal.test(count ~ spray, data = InsectSprays)
# 대립가설: 스프레이간의 성능차이가 있다.
```

```{r}
### 분산 분석
str(PlantGrowth)
PlantGrowth

####### 원 데이터 csv로 출력 #############
write.table(PlantGrowth, "/home/jw/aov.csv")

# 일원배치 분산분석 (oneway Analysis Of Variance : ANOVA)
# ->여러 독립표본 평균을 비교할 때 사용한다.

# 분산분석에서 귀무가설은 다음과 같다.
# H0 : 모든 집단의 평균은 다 같다.
# 
# 따라서, 대립가설은 다음과 같이 된다.
# H1 : 집단의 평균이 다 같지는 않다(집단 중 적어도 어느 하나의 평균이 다르다)

############ 등분산성(동질성) 검정 #####################
bartlett.test(weight ~ group, data = PlantGrowth)  # p-value = 0.2371
with(PlantGrowth, var.test(weight, group))  # p-value = 0.3675
attach(PlantGrowth); var.test(weight, group)
# 귀무가설인 '종속변수의 분산은 모든 집단에서 서로 같다'를 기각하지 못한다
# 즉, 등분산성을 만족한다

######### 집단 간 평균 비교 ###############
#tapply(group, weight, mean)
tapply(weight, group, mean)
#  ctrl  trt1  trt2 
#  5.032 4.661 5.526 

boxplot(weight ~ group, data = PlantGrowth, main = "PlantGrowth data",
        ylab = "Dried weight of plants", col = "lightgray",
        notch = TRUE, varwidth = TRUE)

######## 검정하기 #####
# 방법1
oneway.test(weight ~ group, data = PlantGrowth)
  # p-value = 0.01739 
  # 투여한 약의 종류가 식물의 무게에 영향을 끼친다.

# 방법2
aov.out1 = aov(weight ~ group, data = PlantGrowth)
summary(aov.out1)
# group p-value 0.0159

summary.lm(aov.out1)
# p-value
# grouptrt1   0.1944    
# grouptrt2   0.0877 .
# Adjusted R-squared:  0.2096 

anova(lm(weight ~ group, data = PlantGrowth))
# group p-value 0.0159
```

