---
output:
  md_document:
    variant: markdown_github
---

Pearson의 상관계수: 보통의 상관관계계수 (연속형 변수)
Spearman의 순위상관계수: 두 값의 순위를 이용해 계산 (이산형 자료)
Kendall: 부합쌍 / 비부합쌍의 비율

상관분석의 가정
-선형성
-등분산성
-정규성
-독립성

```{r}
cor.test(1:5, 2:6)
plot(1:5, 2:6)

cor.test(1:5, c(3,3,3,3,3))

plot(1:5, 5:1)
cor.test(1:5, 5:1)
```

```{r}
# 상관분석의 그래프 분석
str(airquality)
airquality_1 <- airquality[ , c(1:4)]
sum(is.na(airquality_1$Ozone))
cor(airquality_1)

airquality_2 <- na.omit(airquality_1)
(airquality_cor <- cor(airquality_2))
```

```{r}
install.packages("corrplot", repos="http://cran.nexr.com/")
```

```{r}
library(corrplot)
plot(airquality_2)

corrplot(airquality_cor, method = "circle")
corrplot(airquality_cor, method = "square")
corrplot(airquality_cor, method = "ellipse") # 가장 보기 좋음
corrplot(airquality_cor, method = "number")
corrplot(airquality_cor, method = "shade")
corrplot(airquality_cor, method = "pie")
```

```{r}
install.packages("eiwild", repos="http://cran.nexr.com/")
```

```{r}
library(eiwild)
data(topleveldat)
```

```{r}
form <- cbind(CSU_2, SPD_2, LINK_2, GRUN_2) ~ cbind(CSU_1, SPD_1, Link_1)
set.seed(1234)
out1 <- indAggEi(form=form, aggr=aggr, indi=indi, IDCols=c("ID","ID"),
               sample=1000, thinning=2, burnin=100, verbose=100)
out2 <- indAggEi(form=form, aggr=aggr, indi=indi, IDCols=c("ID","ID"),
                 sample=1000, thinning=2, burnin=100, verbose=100)
out3 <- indAggEi(form=form, aggr=aggr, indi=indi, IDCols=c("ID","ID"),
                 sample=1000, thinning=2, burnin=100, verbose=100)
out4 <- indAggEi(form=form, aggr=aggr, indi=indi, IDCols=c("ID","ID"),
                 sample=1000, thinning=2, burnin=100, verbose=100)

eiList <- list(out1, out2, out3, out4)

comPlot(eiList, whichCell=1, whichPlot=1)
comPlot(eiList, whichCell="counts.CSU_1.CSU_2", whichPlot=1)
comPlot(eiList, whichCell=1, whichPlot=1, smooth=TRUE)
comPlot(eiList, whichCell=1, whichPlot=2)
comPlot(eiList, whichCell=1, whichPlot=3)
comPlot(eiList, whichCell=1, whichPlot=4)
comPlot(eiList, whichCell=1, whichPlot=4)
comPlot(eiList, 1, 3, whichParam="alphaDraws")
comPlot(eiList, "alpha.CSU_1.CSU_2", 3, whichParam="alphaDraws")

```

```{r}
#cor(iris[ , 1:4]) # pearson 방법
cor(iris[ , 1:4], method = 'pearson')
cor(iris[ , 1:4], method = 'spearman')
cor(iris[ , 1:4], method = 'kendall')
corrplot(cor(iris[ , 1:4]), method = 'ellipse')
```

```{r}
symnum(cor(iris[ , 1:4]))
# B가 제일 큰 상관관계를 보이는 것
```

```{r}
install.packages('corrgram', repos="http://cran.nexr.com/")
```

```{r}
library(corrgram)
corrgram(iris, upper.pane = panel.conf)
corrgram(iris, upper.pane = panel.pie)
corrgram(iris, upper.pane = panel.shade)
corrgram(iris, upper.pane = panel.bar)
corrgram(iris, upper.pane = panel.cor)
corrgram(iris, upper.pane = panel.ellipse)
corrgram(iris, upper.pane = panel.pts)
```

```{r}
cor.test(c(1, 2, 3, 4, 5), c(1, 0, 3, 4, 5), method = 'pearson')
cor.test(c(1, 2, 3, 4, 5), c(1, 0, 3, 4, 5), method = 'spearman')
cor.test(c(1, 2, 3, 4, 5), c(1, 0, 3, 4, 5), method = 'kendall')
```

