---
output:
  md_document:
    variant: markdown_github
---

```{r}
x <- -5:5
if(x[1] > 0) {sqrt(x[1])} else {print("NA")}
```

```{r}
ifelse(x >= 0, sqrt(x), NA)
```
```{r}
getwd()
```

```{r}
AA = 'tttt'
switch(AA, foo = {print('foo')}, bar = {print('bar')}, {print('default')})
```
```{r}
name <- c("kim", "lee", "choe", "park")
which(name == "choi")
```

```{r}
foo = seq(1, 100, by = 2)
foo.squared = NULL
for(i in 1:50) {foo.squared[i] = foo[i] ^ 2}
#foo.squared[2]
```

```{r}
for(i in 1:50) {print(foo.squared[i])}
```
```{r}
I <- 10
#while(I < 10) {}
while(I > 1) {cat(I, "the iteration \n"); I <- I - 1}
```

```{r}
i <- c(1:10)
for(n in i) {}
for(n in i) {if (n %% 2 == 1) {next} else print(n)}
```

```{r}
cnt <- 1
repeat {print(cnt); cnt <- cnt + 2; if(cnt > 15) break}
```
# creating function
```{r}
summation = function(x) {
  result = 0;
  for(i in 1:length(x)){
    result <- result + x[i]
  }
  return(result)
}
```

```{r}
y <- 1:10
summation(y)
#print(summation(y))
```
```{r}
gugu <- function(i, j) {
  mul = NULL
  for(a in 1:length(i)){
    for(b in 1:length(j)){
      mul <- a * b
      print(mul)
    }
  }
}
```

```{r}
gugu(c(1:9), c(2:9))
```

```{r}
gugu2 <- function(i, j){
  for(x in i){
    cat("**", x, "but \n")
    
  }
}
```

```{r}
score <- matrix(nrow = 4, ncol = 5, byrow = TRUE)
colnames(score) <- c("kor","eng", "math", "stu_tot", "avg")
row.names(score) <- c("kim", "lee", "park", "subject_tot")

# input score
for(i in 1:3){
  for(j in 1:3){
    score[i,j] = sample(1:100, 1, replace = TRUE)
    #i = i + 1
  }
}

# stu_tot
for(i in 1:3){
  score[i,4] = sum(score[i,1:3])
}

# avg 
for(i in 1:3)
  score[i,5] = round(mean(score[i,1:3]), 3)

# subject_tot
for(j in 1:5){
  score[4, j] = sum(score[1:3, j])
}
score

# comment avg
a <- matrix(nrow = 4, ncol = 1, byrow = TRUE)

for(i in 1:3){
  if (score[i,5] > 80){
    a[i] <- 'NICE'
  }
  else a[i] <- 'NORMAL'
}
score <- cbind(score, (a[1:4]))
score
```
```{r}
example("plot")
```

