---
output:
  md_document:
    variant: markdown_github
---

```{r}
# 연관분석 apriori
install.packages('arules', repos="http://cran.nexr.com/")
install.packages('arulesViz', repos="http://cran.nexr.com/")
```

```{r}
library(arules)
library(arulesViz)

data('AdultUCI')
dim(AdultUCI)
AdultUCI[1:2, ]
str(AdultUCI)
# 변수조정 - 필요없는 변수값 제거하고 factor화 (복잡한 계산을 줄이고 정확성을 높이기 위해)
# remove attributes
AdultUCI[['fnlwgt']] <- NULL
AdultUCI[['education-num']] <- NULL

## map metric attributes
# 수치형 변수의 값들을 factor화
table(AdultUCI$age)
AdultUCI[['age']] <- ordered(cut(AdultUCI[['age']], 
      c(15, 25, 45, 65, 100)), 
      labels = c('Young', 'Middle-aged', 'Senior', 'Old'))

AdultUCI[["hours-per-week"]] <- ordered(cut(AdultUCI[["hours-per-week"]], 
      c(0, 25, 40, 60, 168)), 
      labels = c("Part-time", "Full-time", "Over-time", "Workaholic"))

AdultUCI[["capital-gain"]] <- ordered(cut(AdultUCI[["capital-gain"]], 
      c(-Inf, 0, median(AdultUCI[["capital-gain"]][AdultUCI[["capital-gain"]] > 0]), Inf)), 
      labels = c("None", "Low", "High"))

AdultUCI[["capital-loss"]] <- ordered(cut(AdultUCI[["capital-loss"]], 
      c(-Inf, 0, median(AdultUCI[["capital-loss"]][AdultUCI[["capital-loss"]] > 0]), Inf)), 
      labels = c("none", "low", "high"))

Adult <- as(AdultUCI, "transactions") # 클래스 강제 변환
inspect(head(Adult))
image(Adult)
#==========================================================================================
adult_rules <- apriori(Adult, 
                 parameter = list(supp = 0.7, conf = 0.9, minlen=2, target = "rules"))

adult_rules.sorted <- sort(adult_rules, by="lift"); inspect(adult_rules.sorted)
inspect(adult_rules)
plot(adult_rules, method = "graph")
#==========================================================================================
adult_rules2 <- apriori(Adult, 
      parameter = list(supp=0.35, conf=0.8, minlen=2, target="rules"), 
      appearance = list(rhs=c("sex=Male", "sex=Female"), default="lhs"))

adult_rules.sorted <- sort(adult_rules2, by="lift"); inspect(adult_rules.sorted)
inspect(adult_rules2)
plot(adult_rules2)
```

