---
output:
  md_document:
    variant: markdown_github
---


```{r}
x <- seq(1, 10, .1)
plot(x, dchisq(x, 6), type = "l")
```

```{r}
#귀무가설: 기대치와 관찰치는 차이가 없다 = 맥주종류에 따른 선호도는 차이가 없다.
#대립가설: 기대치와 관찰치는 차이가 있다 = 맥주종류에 따른 선호도는 차이가 있다.
data <- textConnection(
  "맥주종류 관측도수
  1 12
  2 30
  3 15
  4 7
  5 16")
x <- read.table(data, header = T)
x
#chisq.test(x$맥주종류)
chisq.test(x$관측도수)
```
```{r}
install.packages("MASS", repos="http://cran.nexr.com/")
library(MASS)
str(survey)
head(survey[c("Sex", "Exer")])

#교차분석표
xtabs(~ Sex+Exer, data = survey)
```

```{r}
chisq.test(xtabs(~ Sex+Exer, data = survey))
```

```{r}
survey$Exer
xt <- xtabs(~ Sex+Exer, data = survey)
class(xt)
mode(xt)

margin.table(xt, 1) # 행의 주변합
margin.table(xt, 2) # 열의 주변합
margin.table(xt)

class(xt)
mode(xt)
rowhap <- prop.table(xt, 1)
prop.table(xt, 2)
prop.table(xt)
margin.table(rowhap, 1)
```
```{r}
# 글씨를 왼손으로 쓰는 사람과 오른손으로 쓰는 사람의 비율이 30:70인지 확인하고 싶다.
table(survey$W.Hnd)
chisq.test(table(survey$W.Hnd), p = c(.3, .7))
#chisq.test(table(survey$W.Hnd))
#chisq.test(xtabs(~ W.Hnd, data = survey))
```

```{r}
# 귀무가설: 글자를 쓰는 손과 박수 칠 때 오는 손이 독립이다.
# 대립가설: 글자를 쓰는 손과 박수 칠 때 위에 오는 손이 관계가 있다.

# Chi-squared approximation may be incorrect
# 표본수가 적거나 표본이 분할표의 특정 셀에 지나치게 몰려 있을 경우 발생

xtabs(~W.Hnd+Clap, data = survey)
chisq.test(xtabs(~W.Hnd + Clap, data = survey))
fisher.test(xtabs(~W.Hnd + Clap, data = survey))
```
```{r}
# 이항분포
# binom.test(x, n, p = 0.5, alternative = c("two.sided", "less", "greater"), conf.level = 0.95)

binom.test(c(125, 9), p = 0.7)
binom.test(125, 134, p = 0.7)

binom.test(c(136, 14), 150, p = 0.8)

binom.test(c(136, 14), p = 0.8, alternative = "two.sided", conf.level = 0.95)

# 단축 검증
binom.test(c(136, 14), p = 0.8, alternative = "greater", conf.level = 0.95)

```

```{r}
c(125, 9)
```

```{r}
# 두 집단 비율 검정: prop.test()
# 귀무가설: PT교육(방법1)과 코딩교육(방법2) 간에는 만족도의 차이가 없다.
# 대립가설: 교육방법에 따라 만족도의 차이가 있다.(양측검정일 경우에)
# 결론: 교육방법에 따라 만족도의 차이가 존재한다.
prop.test(c(105, 130), c(140, 140))
prop.test(c(105, 130), c(140, 140), alternative = "two.sided", conf.level = 0.95)

# 단측검정
# 대립가설: 방법1이 방법2보다 만족도가 더 높다?
prop.test(c(105, 130), c(140, 140), alternative = "greater", conf.level = 0.95)
prop.test(c(105, 130), c(140, 140), alternative = "less", conf.level = 0.95)
```

```{r}
data <- textConnection(
  "만족 불만족
  105 35
  130 10
  ")
x <- read.table(data, header = T)
x
chisq.test(x$만족)
```
```{r}
# 맥나마 검정
# 사건 전후의 성향 변화를 알아보는 경우 수행
# 벌금 부과하기 시작한 후 안전벨트 착용자 수의 변화
# 선거 유세를 하고 난 후 지지율 변화
# mcnemar.test()

#performance <- matrix(c(794, 86, 150, 570), nrow = 2, dimnames = list("찬반  " = c("찬성", "반대"), "시행순서" = c("1차", "2차")))
#performance
# mcnemar.test(performance)
# 대립가설 채택

######################################################################################################
## Presidential Approval Ratings.
##  Approval of the President's performance in office in two surveys,
##  one month apart, for a random sample of 1600 voting-age Americans.
Performance <-
matrix(c(794, 86, 150, 570),
       nrow = 2,
       dimnames = list("1st Survey" = c("Approve", "Disapprove"),
                       "2nd Survey" = c("Approve", "Disapprove")))
Performance
mcnemar.test(Performance)
margin.table(Performance, 1)
margin.table(Performance, 2)
## => significant change (in fact, drop) in approval ratings
```

```{r}
# SHAPRIO TEST (정규성 검정)
# 정규성을 만족하면 그 다음은 t.test(모수) 혹은 wilcoxon.test(비모수)

# 귀무가설: 데이터가 정규분포를 따른다
# 대립가설: 데이터가 정규분포를 따르지 않는다.
shapiro.test(rnorm(1000))
# p-value가 0.05보다 크기 때문에 정규분포를 따른다고 할 수 있다.
# 데이터가 정규분포를 따른다는 귀무가설을 기각할 수 없다.

# 균일분포에서도 정규분포

set.seed(1000)
x <- runif(50, min = 2, max = 4)
shapiro.test(x)
# 균등분포는 표본에 따라 정규성을 만족하기도 하고, 정규성을 만족하지 않기도 한다.
```

```{r}
DF <- data.frame ( x = runif (260000) , y = rep ( LETTERS , each =10000) )
head(DF)
```

```{r}
# 단일 집단 평균 검정 - 가설 검정

# 양측검정
# 귀무가설: 표본평균은 모집단평균과 동일하다.
# 대립가설: 표본평균은 모집단평균과 동일하지 않다.
t.test(x , mu = 5.2, alter = "two.side", conf.level = 0.95)

# 단측검정
result <- t.test(x, mu = 5.2, alter = "greater", conf.level = 0.95)
result
result$p.value
```

```{r}
# 귀무가설: a와 모집단평균은 동일하다.
a = c(65, 78, 88, 55, 48, 95, 66, 57, 79, 82)
mean(a)
t.test(a, mu = 88, conf.level = 0.95)
```

```{r}
require(graphics)

# 두 표본 간의 평균 비교
# 귀무가설: 두 표본의 평균은 동일하다
# 대립가설: 두 표본의 평균은 동일하지 않다.
t.test(1:10, y = c(7:20))      # P = .00001855
t.test(1:10, y = c(7:20, 200)) # P = .1245    -- NOT significant anymore

t.test(1:10, y = 1:10)

## Classical example: Student's sleep data
plot(extra ~ group, data = sleep)

## Traditional interface
with(sleep, t.test(extra[group == 1], extra[group == 2]))

## Formula interface
t.test(extra ~ group, data = sleep)

sleep1 <- with(sleep, extra[group == 2] - extra[group == 1])
summary(sleep1)
require(stats)
stripchart(sleep1, method = "stack", xlab = "hours",
           main = "Sleep prolongation (n = 10)")
boxplot(sleep1, horizontal = TRUE, add = TRUE,
        at = .6, pars = list(boxwex = 0.5, staplewex = 0.25))
```

```{r}
x <- 1:10
y <- c(7:20)
z <- c(7:20, 200)
# 귀무가설: 2개의 표본의 분산이 동일하다.(다르다고 할 수 없다.)
# 대립가설: 2개의 표본의 분산이 동일하지 않다.
var.test(x, y)
var.test(x, z)

t.test(x, y)
t.test(x, z)
```

