---
output:
  md_document:
    variant: markdown_github
---

```{r}
# 주성분 분석의 원리
x <- 1:10
y <- x + runif(10, min = -0.5, max = 0.5)
z <- x + y + runif(10, min = -10, max = 10)

(data <- data.frame(x, y, z))
pr <- princomp(data)
summary(pr)
screeplot(pr , type = c("barplot", "lines"), max(10, length(pr)))
```

```{r}
cor.test(x, y)

library(psych)
cor(data)

library(corrgram)
corrgram(data, upper.pane = panel.ellipse)
```

```{r}
library(datasets)
pairs(USArrests, panel = panel.smooth, main = "USArrests data")
US.prin <- princomp(USArrests, cor = TRUE)
summary(US.prin)
screeplot(US.prin, npcs = 4, type = 'lines')
loadings(US.prin)  # 네개의 변수가 주성분 comp1~4까지 기여하는 가중치 제시
US.prin$scores
```

```{r}
# 이메일로 받은 데이터
(securities <- read.csv('/home/jw/Documents/[RStudio] - acorn 수업/secu_com_finance_2007.csv', header = TRUE, fileEncoding = 'EUC-KR'))
sec.prin <- princomp(securities[2:6], cor = TRUE)
summary(sec.prin)
screeplot(sec.prin, npcs = 5, type = 'lines')
loadings(sec.prin)
print(sec.prin)
cor(securities[2:6])
```

```{r}
# 요인분석
install.packages('nFactors', repos="http://cran.nexr.com/")
library(nFactors)
```

```{r}
## ................................................
## SIMPLE EXAMPLE OF THE BENTLER AND YUAN PROCEDURE
# Bentler (1996, p. 309) Table 2 - Example 2 .............
n=649
bentler2<-c(5.785, 3.088, 1.505, 0.582, 0.424, 0.386, 0.360, 0.337, 0.303,
  0.281, 0.246, 0.238, 0.200, 0.160, 0.130)
results <- nBentler(x=bentler2, N=n, details=TRUE)
results
# Two different figures to verify the convergence problem identified with
# the 2th component
bentlerParameters(x=bentler2, N=n, nFactors= 2, graphic=TRUE,
  typePlot="contourplot",
  resParx=c(0,9), resPary=c(0,9), cor=FALSE)

bentlerParameters(x=bentler2, N=n, nFactors= 4, graphic=TRUE, drape=TRUE,
  resParx=c(0,9), resPary=c(0,9),
  scales = list(arrows = FALSE) )

plotuScree(x=bentler2, model="components",
  main=paste(results$nFactors,
  " factors retained by the Bentler and Yuan's procedure (1996, p. 309)",
  sep=""))
```

```{r}

##----------------------------------------------------------------------
## 차원축소(dimension reduction) : (1) PCA(Principal Component Analysis)
##----------------------------------------------------------------------

# csv 파일 불러오기 (file importing)
secu_com_finance_2007 <- read.csv('/home/jw/Documents/[RStudio] - acorn 수업/secu_com_finance_2007.csv', header = TRUE, stringsAsFactors = FALSE)
# V1 : 총자본순이익율
# V2 : 자기자본순이익율
# V3 : 자기자본비율
# V4 : 부채비율
# V5 : 자기자본회전율
```

```{r}
# 평균과 표준편차를 가지고 표준화(standadization)한 데이터를 사용합니다. 그래야 scale이 다른 문제로 인한 데이터 왜곡을 피할 수 있기 때문입니다.

# 표준화 변환 (standardization)
secu_com_finance_2007 <- transform(secu_com_finance_2007, 
                                  V1_s = scale(V1), 
                                  V2_s = scale(V2), 
                                  V3_s = scale(V3), 
                                  V4_s = scale(V4),
                                  V5_s = scale(V5))
```



