---
output:
  md_document:
    variant: markdown_github
---

```{r}
honeymoon <- c(12, 14, 8, 9)
names(honeymoon) <- c("하와이", "동남아", "유럽", "기타")
pie(honeymoon, col = rainbow(4))

per <- round(100 * honeymoon / sum(honeymoon), 1)
lab <- paste(names(honeymoon), "\n", per, "%")

pie(honeymoon, labels = lab, col = rainbow(4), edges = 13, radius = 1, clockwise = TRUE, main = "여행지 분포도", density = 100)

text(0.3, 0.3, "27.9%", col = "black")
text(-0.4, 0.1, "32.6%", col = "black")
text(0.5, -0.3, "20.9%", col = "black")
text(-0.2, -0.5, "18.6%", col = "black")
```

```{r}
weight <- round(rnorm(30, 50, 10))
stem(weight)
stem(weight, scale = 1.0)
stem(weight, scale = 2.0)
stem(weight, scale = 0.5)
```

```{r}
plot(cars$dist, type = "o", cex = 0.5, xlab = "speed", ylab = "dist")
```

```{r}
m <- lm(dist ~ speed, data = cars)
m
plot(cars); abline(m)
p <- predict(m, interval = "confidence")
head(p)
```

```{r}
x <- c(cars$speed, tail(cars$speed, 1), rev(cars$speed), cars$speed[1])
y <- c(p[, "lwr"], tail(p[, "upr"], 1), rev(p[, "upr"]), p[, "lwr"][1])
plot(cars); abline(m); polygon(x, y, col = rgb(.7, .7, .5, .5))
```
```{r}
x <- seq(-2 * pi, 2 * pi, 0.01)
y <- matrix(c(cos(x), sin(x)), ncol = 2)
matplot(x, y, col = c("red", "black"), cex = .2)
matplot(x, y, lyt = c("solid", "dashed"), cex = .2, type = "l")
abline(h = 0, v = 0)
```
```{r}
trees
#fix(trees)
summary(trees)
boxplot(trees)
pairs(trees)
matplot(trees)
```

```{r}
x <- rnorm(1000, mean = 100, sd = 1)
qqnorm(x); qqline(x, lty = 2); abline(h = 100, v = 0)

y <- runif(1000)
qqnorm(y); qqline(y); abline(h = 0.5, v = 0)
```

```{r}
install.packages("mlmRev", repos="http://cran.nexr.com/")
library(mlmRev)
data(Chem97)
library(lattice)
histogram(~gcsescore, data = Chem97)
#histogram(~gcsescore|score, data = Chem97)
#histogram(~gcsescore|factor(score), data = Chem97)
```


